export const ActionTypes = {
  NUM_CLICK: "NUM_CLICK",
  DECIMAL_CLICK: "DECIMAL_CLICK",
  RESET_CLICK: "RESET_CLICK",
  SIGN_CLICK: "SIGN_CLICK",
  EQUAL_CLICK: "EQUAL_CLICK",
  DELETE_CLICK: "DELETE_CLICK",
  ARRAY_CLICK: "ARRAY_CLICK"
}